DROP DATABASE IF EXISTS unifecaf_flix;

CREATE DATABASE IF NOT EXISTS unifecaf_flix;
USE unifecaf_flix;

DROP TABLE IF EXISTS filmes;

CREATE TABLE IF NOT EXISTS filmes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sinopse TEXT NOT NULL,
    ano_lancamento INT,
    diretor VARCHAR(100),
    data_inclusao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO filmes (nome, sinopse, ano_lancamento, diretor) VALUES
('Hackers: Piratas de Computadores', 'Um grupo de jovens hackers descobre um esquema de extorsão corporativa.', 1995, 'Iain Softley'),
('A Rede Social', 'A história da criação do Facebook e as batalhas legais que se seguiram.', 2010, 'David Fincher'),
('Matrix', 'Um programador descobre a verdadeira natureza da realidade.', 1999, 'Lana Wachowski e Lilly Wachowski'),
('O Jogo da Imitação', 'Alan Turing tenta quebrar o código Enigma durante a guerra.', 2014, 'Morten Tyldum'),
('Steve Jobs', 'A trajetória do fundador da Apple.', 2015, 'Danny Boyle'),
('Interestelar', 'Astronautas viajam por um buraco de minhoca para salvar a humanidade.', 2014, 'Christopher Nolan'),
('A Origem', 'Ladrões invadem sonhos para roubar informações.', 2010, 'Christopher Nolan'),
('Clube da Luta', 'Um homem cria um clube secreto de lutas.', 1999, 'David Fincher'),
('Seven', 'Dois detetives perseguem um serial killer.', 1995, 'David Fincher'),
('Garota Exemplar', 'O desaparecimento de uma mulher gera suspeitas.', 2014, 'David Fincher'),
('Blade Runner', 'Um caçador de androides enfrenta dilemas éticos.', 1982, 'Ridley Scott'),
('Blade Runner 2049', 'Um novo blade runner desvenda um segredo.', 2017, 'Denis Villeneuve'),
('Duna', 'Um jovem lidera a luta pelo planeta Arrakis.', 2021, 'Denis Villeneuve'),
('Duna: Parte Dois', 'A continuação da jornada de Paul Atreides.', 2024, 'Denis Villeneuve'),
('Avatar', 'Um ex-fuzileiro vive entre os Na''vi.', 2009, 'James Cameron'),
('Avatar: O Caminho da Água', 'A família Sully enfrenta novas ameaças.', 2022, 'James Cameron'),
('Titanic', 'Um romance a bordo do navio Titanic.', 1997, 'James Cameron'),
('Exterminador do Futuro', 'Um ciborgue viaja no tempo.', 1984, 'James Cameron'),
('O Exterminador do Futuro 2', 'Sarah Connor protege seu filho.', 1991, 'James Cameron'),
('Alien', 'Uma tripulação enfrenta uma criatura mortal.', 1979, 'Ridley Scott'),
('Aliens', 'Ripley retorna para enfrentar os xenomorfos.', 1986, 'James Cameron'),
('Gladiador', 'Um general romano busca vingança.', 2000, 'Ridley Scott'),
('Napoleão', 'A ascensão de Napoleão Bonaparte.', 2023, 'Ridley Scott'),
('O Resgate do Soldado Ryan', 'Soldados procuram um paraquedista na guerra.', 1998, 'Steven Spielberg'),
('Jurassic Park', 'Dinossauros clonados escapam do controle.', 1993, 'Steven Spielberg'),
('O Mundo Perdido', 'Nova expedição à ilha dos dinossauros.', 1997, 'Steven Spielberg'),
('Jurassic World', 'Um novo parque é inaugurado.', 2015, 'Colin Trevorrow'),
('Tubarão', 'Um grande tubarão ameaça uma praia.', 1975, 'Steven Spielberg'),
('E.T.', 'Um garoto faz amizade com um alienígena.', 1982, 'Steven Spielberg'),
('Ready Player One', 'Jovens competem em um mundo virtual.', 2018, 'Steven Spielberg'),
('Minority Report', 'Policiais prendem criminosos antes dos crimes.', 2002, 'Steven Spielberg'),
('Inteligência Artificial', 'Um robô deseja se tornar humano.', 2001, 'Steven Spielberg'),
('Forrest Gump', 'A vida extraordinária de Forrest.', 1994, 'Robert Zemeckis'),
('De Volta para o Futuro', 'Um adolescente viaja para o passado.', 1985, 'Robert Zemeckis'),
('De Volta para o Futuro II', 'Marty visita o futuro.', 1989, 'Robert Zemeckis'),
('De Volta para o Futuro III', 'A aventura chega ao velho oeste.', 1990, 'Robert Zemeckis'),
('Náufrago', 'Um homem sobrevive isolado numa ilha.', 2000, 'Robert Zemeckis'),
('O Poderoso Chefão', 'A história da família Corleone.', 1972, 'Francis Ford Coppola'),
('O Poderoso Chefão II', 'A continuação da saga Corleone.', 1974, 'Francis Ford Coppola'),
('Scarface', 'A ascensão de um traficante em Miami.', 1983, 'Brian De Palma'),
('Os Bons Companheiros', 'A vida no crime organizado.', 1990, 'Martin Scorsese'),
('Cassino', 'Máfia e cassinos em Las Vegas.', 1995, 'Martin Scorsese'),
('O Lobo de Wall Street', 'A ascensão de um corretor ambicioso.', 2013, 'Martin Scorsese'),
('Taxi Driver', 'Um veterano se torna obcecado pela violência.', 1976, 'Martin Scorsese'),
('Ilha do Medo', 'Um detetive investiga um hospital psiquiátrico.', 2010, 'Martin Scorsese'),
('Os Infiltrados', 'Polícia e máfia infiltram agentes.', 2006, 'Martin Scorsese'),
('Batman Begins', 'A origem do Cavaleiro das Trevas.', 2005, 'Christopher Nolan'),
('Batman: O Cavaleiro das Trevas', 'Batman enfrenta o Coringa.', 2008, 'Christopher Nolan'),
('Batman: O Cavaleiro das Trevas Ressurge', 'Batman retorna após anos.', 2012, 'Christopher Nolan'),
('O Grande Truque', 'Dois mágicos disputam fama.', 2006, 'Christopher Nolan'),
('Tenet', 'Agentes manipulam o fluxo do tempo.', 2020, 'Christopher Nolan'),
('Memento', 'Um homem tenta resolver um crime.', 2000, 'Christopher Nolan'),
('Whiplash', 'Um baterista enfrenta um professor exigente.', 2014, 'Damien Chazelle'),
('La La Land', 'Um músico e uma atriz perseguem sonhos.', 2016, 'Damien Chazelle'),
('Top Gun', 'Pilotos treinam para missões aéreas.', 1986, 'Tony Scott'),
('Top Gun: Maverick', 'Maverick retorna como instrutor.', 2022, 'Joseph Kosinski'),
('Missão Impossível', 'Ethan Hunt impede uma conspiração.', 1996, 'Brian De Palma'),
('Missão Impossível 2', 'Nova missão de Ethan Hunt.', 2000, 'John Woo'),
('Missão Impossível 3', 'Ethan enfrenta um traficante.', 2006, 'J.J. Abrams'),
('Missão Impossível: Protocolo Fantasma', 'Equipe tenta evitar uma guerra.', 2011, 'Brad Bird'),
('Missão Impossível: Nação Secreta', 'A caça ao Sindicato.', 2015, 'Christopher McQuarrie'),
('Missão Impossível: Efeito Fallout', 'Uma missão sai do controle.', 2018, 'Christopher McQuarrie'),
('John Wick', 'Um assassino aposentado busca vingança.', 2014, 'Chad Stahelski'),
('John Wick 2', 'John é forçado a retornar.', 2017, 'Chad Stahelski'),
('John Wick 3', 'John foge dos assassinos.', 2019, 'Chad Stahelski'),
('John Wick 4', 'O confronto final.', 2023, 'Chad Stahelski'),
('Velozes e Furiosos', 'Corridas ilegais e ação.', 2001, 'Rob Cohen'),
('Velozes e Furiosos 2', 'Brian retorna às corridas.', 2003, 'John Singleton'),
('Velozes e Furiosos: Desafio em Tóquio', 'Drift no Japão.', 2006, 'Justin Lin'),
('Vingadores', 'Heróis unem forças para salvar o mundo.', 2012, 'Joss Whedon'),
('Vingadores: Era de Ultron', 'Os heróis enfrentam Ultron.', 2015, 'Joss Whedon'),
('Vingadores: Guerra Infinita', 'Thanos busca as joias.', 2018, 'Anthony e Joe Russo'),
('Vingadores: Ultimato', 'A batalha final contra Thanos.', 2019, 'Anthony e Joe Russo'),
('Homem de Ferro', 'Tony Stark cria uma armadura.', 2008, 'Jon Favreau'),
('Capitão América', 'A origem do supersoldado.', 2011, 'Joe Johnston'),
('Thor', 'O deus do trovão é exilado.', 2011, 'Kenneth Branagh'),
('Pantera Negra', 'O rei de Wakanda assume o trono.', 2018, 'Ryan Coogler'),
('Doutor Estranho', 'Um cirurgião descobre as artes místicas.', 2016, 'Scott Derrickson'),
('Guardiões da Galáxia', 'Uma equipe improvável salva a galáxia.', 2014, 'James Gunn'),
('Deadpool', 'Um mercenário ganha poderes.', 2016, 'Tim Miller'),
('Logan', 'Wolverine protege uma jovem mutante.', 2017, 'James Mangold'),
('X-Men', 'Mutantes enfrentam preconceito.', 2000, 'Bryan Singer'),
('X-Men 2', 'Mutantes unem forças.', 2003, 'Bryan Singer'),
('Primeiro Contato', 'Alienígenas chegam à Terra.', 2016, 'Denis Villeneuve'),
('Gravidade', 'Astronautas tentam sobreviver no espaço.', 2013, 'Alfonso Cuarón'),
('Perdido em Marte', 'Um astronauta fica preso em Marte.', 2015, 'Ridley Scott'),
('2001: Uma Odisseia no Espaço', 'Uma jornada cósmica sobre evolução.', 1968, 'Stanley Kubrick'),
('Laranja Mecânica', 'Um jovem violento passa por tratamento.', 1971, 'Stanley Kubrick'),
('O Iluminado', 'Uma família enfrenta forças sobrenaturais.', 1980, 'Stanley Kubrick'),
('Full Metal Jacket', 'A brutalidade da guerra.', 1987, 'Stanley Kubrick'),
('Parasita', 'Duas famílias de classes opostas se cruzam.', 2019, 'Bong Joon-ho'),
('Memórias de um Assassino', 'Detetives investigam assassinatos.', 2003, 'Bong Joon-ho'),
('Snowpiercer', 'Os últimos humanos vivem em um trem.', 2013, 'Bong Joon-ho'),
('Oldboy', 'Um homem busca vingança após anos preso.', 2003, 'Park Chan-wook'),
('Train to Busan', 'Sobreviventes enfrentam zumbis.', 2016, 'Yeon Sang-ho'),
('Coringa', 'A transformação de Arthur Fleck.', 2019, 'Todd Phillips'),
('The Batman', 'Batman investiga assassinatos.', 2022, 'Matt Reeves'),
('Watchmen', 'Heróis investigam uma conspiração.', 2009, 'Zack Snyder'),
('300', 'Espartanos enfrentam o exército persa.', 2006, 'Zack Snyder'),
('Liga da Justiça', 'Heróis unem forças.', 2017, 'Zack Snyder'),
('Homem de Aço', 'A origem do Superman.', 2013, 'Zack Snyder'),
('Mulher-Maravilha', 'A guerreira amazona entra em ação.', 2017, 'Patty Jenkins'),
('Aquaman', 'O herdeiro de Atlântida assume seu destino.', 2018, 'James Wan'),
('Shrek', 'Um ogro embarca numa aventura.', 2001, 'Andrew Adamson'),
('Shrek 2', 'Shrek conhece os sogros.', 2004, 'Andrew Adamson'),
('Kung Fu Panda', 'Um panda se torna guerreiro.', 2008, 'Mark Osborne'),
('Como Treinar o Seu Dragão', 'Um jovem faz amizade com um dragão.', 2010, 'Dean DeBlois'),
('Toy Story', 'Brinquedos ganham vida.', 1995, 'John Lasseter'),
('Toy Story 2', 'Woody é sequestrado.', 1999, 'John Lasseter'),
('Toy Story 3', 'Andy vai para a faculdade.', 2010, 'Lee Unkrich'),
('Toy Story 4', 'Woody reencontra antigos amigos.', 2019, 'Josh Cooley'),
('Procurando Nemo', 'Um peixe procura seu filho.', 2003, 'Andrew Stanton'),
('Procurando Dory', 'Dory busca sua família.', 2016, 'Andrew Stanton'),
('Monstros S.A.', 'Monstros geram energia com sustos.', 2001, 'Pete Docter'),
('Divertida Mente', 'As emoções de uma garota.', 2015, 'Pete Docter'),
('Divertida Mente 2', 'Novas emoções aparecem.', 2024, 'Kelsey Mann'),
('Wall-E', 'Um robô limpa a Terra abandonada.', 2008, 'Andrew Stanton'),
('Up: Altas Aventuras', 'Um idoso realiza um sonho.', 2009, 'Pete Docter'),
('Soul', 'Um músico reflete sobre a vida.', 2020, 'Pete Docter'),
('Os Incríveis', 'Uma família de super-heróis.', 2004, 'Brad Bird'),
('Os Incríveis 2', 'A família retorna à ação.', 2018, 'Brad Bird'),
('Ratatouille', 'Um rato sonha ser chef.', 2007, 'Brad Bird'),
('Coco', 'Um garoto explora o mundo dos mortos.', 2017, 'Lee Unkrich'),
('Encanto', 'Uma família mágica vive na Colômbia.', 2021, 'Jared Bush'),
('Frozen', 'Duas irmãs enfrentam um inverno eterno.', 2013, 'Chris Buck'),
('Moana', 'Uma jovem navega pelo oceano.', 2016, 'Ron Clements'),
('O Rei Leão', 'Um leão enfrenta seu destino.', 1994, 'Roger Allers'),
('Aladdin', 'Um jovem encontra uma lâmpada mágica.', 1992, 'Ron Clements'),
('Mulan', 'Uma jovem assume o lugar do pai na guerra.', 1998, 'Tony Bancroft'),
('Hércules', 'O herói busca seu lugar no mundo.', 1997, 'Ron Clements'),
('Tarzan', 'Um homem criado por gorilas.', 1999, 'Chris Buck'),
('Zootopia', 'Uma coelha policial resolve um caso.', 2016, 'Byron Howard'),
('A Bela e a Fera', 'Uma jovem conhece uma fera encantada.', 1991, 'Gary Trousdale'),
('Pocahontas', 'Uma jovem indígena encontra um explorador.', 1995, 'Mike Gabriel'),
('Lilo e Stitch', 'Uma garota faz amizade com um alienígena.', 2002, 'Chris Sanders'),
('O Sexto Sentido', 'Um garoto vê pessoas mortas.', 1999, 'M. Night Shyamalan'),
('Fragmentado', 'Um homem possui múltiplas personalidades.', 2016, 'M. Night Shyamalan'),
('Corra!', 'Um jovem descobre um segredo perturbador.', 2017, 'Jordan Peele'),
('Nós', 'Uma família enfrenta seus sósias.', 2019, 'Jordan Peele'),
('Não! Não Olhe!', 'Eventos misteriosos ocorrem em um rancho.', 2022, 'Jordan Peele');